### ISSUE TITLE
how to generate the pre-trained data.

### ISSUE THREAD

**Issue by chenzixuan99** [clvrai/skimo#3]
Hi, thanks for sharing this wonderful code!

I would like to ask you how you generated the offline data (https://github.com/clvrai/skimo#download-offline-datasets), as I am trying to generate new pre-training data myself.

**Comment by acl21** [comment]
Thank you for such a well-written code. 

I have a similar question on CALVIN data, do you have the script used to generate the `.h5` files? I see that these `.h5` files are being converted in `scripts/convert_calvin_data.py`. We want to retrain Skimo on CALVIN with and without RGB input as part of our baselines/ablations and the said script would help us a lot.

**Comment by youngwoon** [comment]
Sorry for the late response. We used the original datasets for Kitchen (in D4RL) and CALVIN. For maze, we also use the script in D4RL to generate pre-training data (see https://github.com/Farama-Foundation/D4RL/blob/master/scripts/generation/generate_maze2d_datasets.py).
